name: Monitoreo Satelital y Climático Waraira Repano

on:
  schedule:
    # DISTRIBUCIÓN EQUITATIVA: Se ejecuta cada 4 horas exactas.
    # Usamos el minuto 12 para evitar el colapso de servidores de GitHub en las horas en punto.
    #
    # Equivalencias de horarios (UTC vs Hora Venezuela):
    # Equivalencias de horarios aproximados (VET - Hora Venezuela):
    # 12:12 AM, 02:12 AM, 04:12 AM, 06:12 AM, 08:12 AM, 10:12 AM
    # 12:12 PM, 02:12 PM, 04:12 PM, 06:12 PM, 08:12 PM, 10:12 PM
    - cron: "12 */2 * * *"  
  workflow_dispatch: # Permite ejecutar el script manualmente con un botón

jobs:
  monitorear:
    runs-on: ubuntu-latest # Usamos Linux (más rápido y barato)

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11" # Versión estable y moderna

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar script de monitoreo
        # Definimos las variables de entorno para que Python las pueda leer
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GEE_SERVICE_ACCOUNT_KEY: ${{ secrets.GEE_SERVICE_ACCOUNT_KEY }}
        run: python main.py
